version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - '5000:5000'
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - '8080:8080'
      